# Configuración para el script de renombrar y copiar torrents
source_folder: 'E:\Github\torrents\Cajon de Torrents'
dest_folder: 'E:\Github\torrents_'
torrents_filename: 'torrents_filename.txt'
media_filename: 'media_filename.txt'
